#! /bin/bash

main() {
  local token="$1"

  # assert git repo
  git status 1> /dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo "$(pwd) is not a git repo" 1>&2
    exit 1
  fi

  # assert token provided
  if [[ -z "$token" ]]; then
    echo "No token provided" 1>&2
    echo "$(usage)" 1>&2
    exit 1
  fi

  # assert has origin remote url
  local origin_url="$(git remote get-url origin 2> /dev/null)"
  if [[ -z "$origin_url" ]]; then
    echo "$(pwd) has no origin remote url" 1>&2
    exit 1
  fi

  # update remote url
  local new_origin_url="$(echo "$origin_url" | sed -e "s/\(https\?:\/\/\)\(.*\)\(github\.com.\+\)/\1${token}@\3/")"
  git remote set-url origin "$new_origin_url"
}

usage() {
  echo "Usage: sgt <token>"
}

main "$@"

